### PR TITLE
feat: CRC32 MPEG-2

### PR DESCRIPTION
**Pull request by grabofus**
Add support for CRC32 MPEG-2

### CODE REVIEW

**Comment by grabofus** [comment]
Should resolve https://github.com/alexgorbatchev/crc/issues/65

**Comment by alexgorbatchev** [comment]
Thanks for the PR, I hope to review it sometime next week.

**Review by alexgorbatchev — APPROVED** [review]

**Comment by alexgorbatchev** [comment]
Some file name issues with missing `2` in `mpeg2`, but I can fix that. Thanks!

**Comment by grabofus** [comment]
I had some issues with running the unit tests when I had the `2` suffix in `mpeg2`, although that would've been my preferred way too. Thanks for the merge 🙌

**Pull request merged**
